version: '2.1'
services:
    base:
        image: alpine-node-cmi
        volumes:
            - .:/usr/src/app/
            - ./docker_node_modules:/usr/src/app/node_modules
        ports:
            - "9999:9999"
            - "9229:9229"
        working_dir: /usr/src/app/
    install:
        extends:
            service: base
        command: npm i
    postinstall:
        extends:
            service: base
        command: npm run postinstall
    debug-start:
        extends:
            service: base
        command: node --inspect-brk=0.0.0.0 index.js
    debug-example:
        extends:
            service: base
        command: node --inspect-brk=0.0.0.0 example/index.js
    debug-test-u:
        extends:
            service: base
        command: npm run test:u -- --inspect-brk=0.0.0.0
    debug-test-i:
        extends:
            service: base
        command: npm run test:i -- --inspect-brk=0.0.0.0
    start:
        extends:
            service: base
        command: node index.js
    example:
        extends:
            service: base
        command: node example/index.js
    test-u:
        extends:
            service: base
        command: npm run test:u
    test-i:
        extends:
            service: base
        command: npm run test:i
    test:
        extends:
            service: base
        command: npm t
    bash:
        extends:
            service: base
        command: /bin/sh
